spring.application.name=pcmanager
spring.datasource.url=jdbc:postgresql://localhost:5432/pcmanager
spring.datasource.username=pcmanager
spring.datasource.password=N0m1596.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
